### ISSUE TITLE
[regression] WoW WotLK Classic ~30% less performance since 83a2942

### ISSUE THREAD

**Issue by koplo199** [doitsujin/dxvk#3632]
Using DXVK 2.2 seems to have pretty big perfomance regression (~25/30%) for WotLK Classic, doing a git bisect give the following commit as a culprit: 83a294285e90c65554bc851c4d4a126aa15916a4.

Compiling using the parent commit (242ac20752245d2dac02e9c335fd7c1f36466a58), or using the `master` branch reverting 83a294285e90c65554bc851c4d4a126aa15916a4 (and 14eb469005fd0270d95133e3c83f9e4c5d1f405d to fix compilation errors) makes it work at the right FPS again.

### Software information
World of Warcraft: Wrath of the Lich King Classic
Max settings

### System information
- GPU: NVIDIA 3080
- Driver: 535.98
- Wine version: Wine-GE 8-13

### Log files
Using `DXVK_LOG_LEVEL=debug` and `DXVK_LOG_PATH` set appropriately:

[WoWClassic_dxgi_83a2942.log](https://github.com/doitsujin/dxvk/files/12396427/WoWClassic_dxgi_83a2942.log)
[WoWClassic_d3d11_83a2942.log](https://github.com/doitsujin/dxvk/files/12396428/WoWClassic_d3d11_83a2942.log)

[WoWClassic_dxgi_242ac20(parent).log](https://github.com/doitsujin/dxvk/files/12396429/WoWClassic_dxgi_242ac20.parent.log)
[WoWClassic_d3d11_242ac20(parent).log](https://github.com/doitsujin/dxvk/files/12396430/WoWClassic_d3d11_242ac20.parent.log)

**Comment by Blisto91** [comment]
That sounds very odd. Can you send a screenshot from each commit with `DXVK_HUD=full` ?

**Comment by Blisto91** [comment]
What is your setup like. Do you have multiple GPU's or monitors?
Does anything interesting get printed by Wine.

**Comment by koplo199** [comment]
I only have one GPU and one monitor. What I can report of interesting is that my 3080 is listed twice in the in-game GPU selection menu:

![Screenshot from 2023-08-21 18-10-44](https://github.com/doitsujin/dxvk/assets/85577251/43dfaa4c-c8c4-4841-ad94-155bc21d4b62)

And if I enable DXVK_NVAPI, it correctly detects there's only one GPU, but for some reason reports it as low power:

![Screenshot from 2023-08-21 18-09-44](https://github.com/doitsujin/dxvk/assets/85577251/924aa0b6-1b7d-4ca6-b2e5-118e15d299fc)

This behavior is shared by both good and bad commits. Enabling/Disabling DXVK_NVAPI does not affect performance at all.

**Comment by Blisto91** [comment]
I don't know if it would be helpful here, but might be good if you good make an apitrace for the devs https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

**Comment by koplo199** [comment]
Sorry for the delay, here are the requested logs:
[logs.tar.gz](https://github.com/doitsujin/dxvk/files/12418847/logs.tar.gz)

**Comment by Blisto91** [comment]
Thank you for the logs.
Could i get you to try and run the game through Proton in Steam as a non steam game? Hopefully you should just be able to add the battlenet or wow exxe itself directly from your current prefix install without needing to touch anything else.
If the issue still shows then could you post a Proton log with `PROTON_LOG=+system,+xrandr,+x11drv %command%`

**Comment by koplo199** [comment]
As I was using the flatpak version of both Steam and Bottles so it required a bit more steps to share the install directory between them (details below), but I can confirm it also happens on a regular Proton Experimental using a fresh prefix, here are the logs:
[steam-15655447108700340224.log.tar.gz](https://github.com/doitsujin/dxvk/files/12427494/steam-15655447108700340224.log.tar.gz)


<details>




I had to launch Steam with `--filesystem=~/.var/app/com.usebottles.bottles/data/bottles` in order to allow access to the bottle `Program Files (x86)`, and then just symlinked it inside the the fresh Proton prefix so that the WoW install and its configuration files were the exact same between the two environments.


</details>

**Comment by doitsujin** [comment]
Either way, it's pretty clear that the performance regression is the symptom of another issue elsewhere, since games **should not** query your monitor setup every single frame. The commit in question slowing this down is expected, but the whole thing shouldn't be happening in the first place.

**Comment by koplo199** [comment]
It sure _shouldn't_ happen, but it unfortunately _does_ happen. Would a workaround for this kind of situation be conceivable? Looking at the commit, it seems the change were made for system possessing an iGPU, could the old behavior be restored for system who don't?

**Comment by doitsujin** [comment]
That doesn't fix the underlying issue.

**Comment by koplo199** [comment]
It doesn't, but if the underlying issue is on the Blizzard side of things there's not much else that can be done I assume. ANd either way it would solve the performance impact, which seems like an acceptable trade-off.

**Comment by Blisto91** [comment]
@koplo199 Sorry for the chasing back and forth here. Could you also provide logs from the commit prior to the offending one like in your opening post, but with `WINEDEBUG=+pid,+loaddll,+timestamp,+seh,+xrandr,+system`

**Comment by koplo199** [comment]
@Blisto91 Sure, here are the new logs:
[logs.tar.gz](https://github.com/doitsujin/dxvk/files/12436894/logs.tar.gz)

I noticed something new, and completely unexpected: the flip model for WoW WotLK is broken, it can be seen on the first two screenshots by observing the `BLIT` at the top left hidden behind the DXVK HUD. But where the black magic begins is that it breaks the flip model for any other game! To clarify this is what is happening:
- Steam (flatpak), run game and observe the flip model is working by seeing the `FLIP` indicator
- Bottles (flatpak), run WoW WotLK and observe the flip model is broken by seeing the `BLIT` indicator
- Steam (flatpak), run the same game and observe the flip model is now broken by seeing the `BLIT` indicator

Bonus, running [gl-sync-demo](https://github.com/dahenry/gl-gsync-demo) on the host shows no such regression...

**Comment by doitsujin** [comment]
Reminder that the decision whether to flip or not on presentation depends on interactions between your compositor and your graphics driver, DXVK does not have any way to directly influence this.

**Comment by koplo199** [comment]
Yes, I'll report the `FLIP` issue to NVIDIA directly.

**Comment by Blisto91** [comment]
@koplo199 So i can myself reproduce a big perf drop when i change my vendor id to not match my GPU (7900 xtx). 
But i'm confused as to why you still have a drop even when using nvapi as that should show your vendor id correctly as Nvidia. Could you also send a log where you have that enabled?

**Comment by koplo199** [comment]
@Blisto91 Sure, here are the logs using `DXVK-NVAPI` 0.6.3 and `WINEDEBUG=+pid,+loaddll,+timestamp,+seh,+xrandr,+system`:
[logs.tar.gz](https://github.com/doitsujin/dxvk/files/12454074/logs.tar.gz)

Note: the `dxvk.conf` only contains `dxgi.nvapiHack = False`, and the env variable `DXVK_ENABLE_NVAPI` is set to 1.

**Comment by gofman** [comment]
It would be most interesting to see how that goes with Proton without anything custom (possibly PROTON_ENABLE_NVAPI=1). That is, e. g. , without flatpak which is not a supported Proton configuration. Thing is, as this (afaik) is not the issue for everyone, so probably something should be triggering that in specific configuration.

**Comment by koplo199** [comment]
I might have an interesting new information: it seems WoW _never_ attempts to load nvapi librairies on Linux. It is hinted in-game by the message `NVAPI is disabled on Wine` under the Low Latency Mode dropdown setting, and confirmed by the different logs where no `loaddll` entries are found for neither `nvapi.dll` or `nvapi64.dll` (and no DXVK-NVAPI messages are printed, even with `DXVK_NVAPI_LOG_LEVEL=info`).

Maybe WoW relies on `nvapi` to correctly detects NVIDA GPUs, and by disabling it on Linux so early in the process it breaks its own detection mechanism? It would explains why an RTX 3080 is incorrectly shown as `(Low Power)`, and @Blisto91 maybe this is also why there still is a big drop in performance when reporting a matching vendor id for NVIDIA GPUs but not for AMD ones?

**Comment by gofman** [comment]
Thanks for the interesting find. So it looks like that the game is somewhat broken on Wine specific path, on which path it requeries dxgi output config each frame with Nvidia. This is not too much performant before the blamed commit as well, nor on Windows, although output enumeration became much slower with the blamed commit. I think mostly because in the current Proton (and in Wine before commit c2c9112bf8896d49a6af1ca1f73e563c5a7f909c) QueryDisplayConfig is much slower than EnumDisplayMonitors which was used before. Unfortunately the referenced commit caused massive regressions (not the direct commit fault, it triggered a lot of pre-existing issues). Those issues are believed to be fixed in Wine upstream now but that's a lot of sensitive changes which we cannot pull to Proton at once (also given that properly behaving games which avoid costly display config re-evaluation each frame don't suffer from this).

So I hope that it will be greatly improved once we get c2c9112bf8896d49a6af1ca1f73e563c5a7f909c and followups in Proton. Before that, if it is possible to check with upstream Wine + dxvk, it would be interesting if the issue is not there (or there to much less extent). Also maybe a temporary workaround using WINE_HIDE_NVIDIA_GPU=1 (instead of PROTON_ENABLE_NVAPI) will help.

**Comment by Blisto91** [comment]
> It would explains why an RTX 3080 is incorrectly shown as `(Low Power)`, and @Blisto91 maybe this is also why there still is a big drop in performance when reporting a matching vendor id for NVIDIA GPUs but not for AMD ones?

On that specific note. Interestingly i get the same "Low Power" marker on my main GPU when i spoof another vendor id than the one i have.
<details>
  <summary>Screenshots</summary>
  
#### Spoofed another vendor than AMD. See also bad perf.
![Screenshot_20230905_193146](https://github.com/doitsujin/dxvk/assets/47954800/c1d186ad-b0ec-429f-863c-19fb99b092ca)

#### No spoof
![Screenshot_20230905_193606](https://github.com/doitsujin/dxvk/assets/47954800/ea7fd597-403d-4509-97a5-617e952e0837)
</details>

**Comment by Blisto91** [comment]
@koplo199 Could you when you have time test this Proton build in Steam with and without nvapi enabled? Just need to check something. <https://drive.proton.me/urls/ANJ8ACCZA8#4g9qbdLUTpq1>
If you extract it into `~/.steam/steam/compatibilitytools.d/` it will show up as a comparability option. Steam will need a restart if already running

**Comment by insunaa** [comment]
I can confirm that I'm affected by this regression as well, for me it went from ~300fps in dxvk 2.2 to ~60fps with dxvk 2.3
The game is only actually playable when switching the graphics API from dx11 to dx12 and using vkd3d instead. First time that vkd3d is faster than dxvk for me.

**Comment by Blisto91** [comment]
Are you sure this is the same issue? I'm a bit confused if you are saying this started in 2.2 or 2.3. The commit written about here was introduced in 2.2.
Please post a log

**Comment by insunaa** [comment]
I would, but dxvk doesn't write logs despite having log level set to debug and log path set to a universally writable directory

**Comment by koplo199** [comment]
@Blisto91 I confirm that using that build (alongside `dxgi.useMonitorFallback=True`)  _entirely_ fixes the issue!

(And sorry I missed your previous [comment](https://github.com/doitsujin/dxvk/issues/3632#issuecomment-1709185156) about a test with a particular Proton build, I was able to test it now on a regular Steam installation and for what it's worth it didn't seem to change anything)

**Comment by Blisto91** [comment]
> Does it mean the workaround can now be added to config.cpp

We are a bit weary of adding it built in for every game as it has the potential of breaking some games in multi monitor or multi GPU setups.

**Comment by koplo199** [comment]
Understandable, I just want to add that from my last testings the performance drop was really significative: ~50 FPS without the workaround and ~100 FPS with it activated. It was still very much playable, but that's with a 3080 at ~1440p; for some users it might cross the boundary between playable and unplayable, so I really don't know what would be the best option here.

As the regression seems to mainly affect NVIDIA cards, could it be activated for World of Wacraft by default if an NVIDIA card is detected (or with an Intel/AMD card if their `hideXXXGpu` option is enabled, as it apparently affect them too in that case)?
Or maybe more simply, couldn't it be made te be activated for all games when only one monitor/GPU is detected?

**Comment by Milor123** [comment]
@koplo199 Try use my settings [https://gist.github.com/Milor123/351517ec9741786b910f874826943975](https://gist.github.com/Milor123/351517ec9741786b910f874826943975)

**Comment by Blisto91** [comment]
As said above the config `dxgi.useMonitorFallback` is specifically meant to work around this issue.
It should be solved properly in Proton 9 once it is out.

**Comment by Blisto91** [comment]
@koplo199 @insunaa @kerriganx Friendly ping. I checked it out with my new Nvidia GPU and it seemed fine with Proton 9

**Comment by koplo199** [comment]
Sorry for the delay, I was/am unable to test but there's no reason to believe it isn't fixed by Proton 9.

Many thanks to everyone involved in the resolution of the issue!

**Comment by Blisto91** [comment]
The dxvk workaround for this specific issue was pulled out because the proper fix was included in Proton 9 (and upstream Wine 9)

**Comment by insunaa** [comment]
Lutris does not have Wine 9 or Proton 9 and probably never will, either. Is the suggested fix to downgrade to a previous version of dxvk?

**Comment by Blisto91** [comment]
If you are unable to use a newer Wine then yes I'd stick to 2.3.1 for now.

**Comment by insunaa** [comment]
> If you are unable to use a newer Wine then yes I'd stick to 2.3.1 for now.

Alright, thank you.

**Comment by K0bin** [comment]
As far as I understand it, the developers of various Linux game launchers are working together on providing a modern runtime to run recent versions on Wine on top. Hopefully this will result in having Wine 9 in Lutris at some point.

https://github.com/Open-Wine-Components/umu-launcher
