### ISSUE TITLE
DXVK 1-10-3 not work in WINE 10.14

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#5196]
Hello.
Thanks for reading my topic.
Here Ubuntu 24.04.1 and WINE 10.14.
DXVK 1.10.3 is the last version that works with my video card nvidia driver 470.
DXVK 1.10.3 is installed without errors messages, but not works.
Not is possible load some games and is showed the message

002c:fixme:winediag:loader_init wine-staging 10.14 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0024:fixme:winediag:loader_init wine-staging 10.14 is a testing version containing experimental patches.
0024:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0134:err:module:import_dll Loading library d3d9.dll (which is needed by L"Z:\\tmp\\5\\Doom\\gzdoom.exe") failed (error c000007b).
0134:err:module:loader_init Importing dlls for L"Z:\\tmp\\games\\doom\\doom.exe" failed, status c0000135

The game not use d3d9.
Perhaps WINE 10.X new wow64 mode break DXVK 1.10.3.
WINE 10.14 not installing DXVK start the game in D3D10 or Vulkan without issues.
In WINE current version is need install DXVK 1.10.3 ?
WINE 10.14 D3D10 and Vulkan implementation is enough to run some games and not need install DXVK 1.10.3 ? If not have any way to fix that issue ?

Have an nice day.

**Comment by doitsujin** [comment]
This is a DLL loading issue before any DXVK code is even *run*, clearly something isn't set up properly on your end.

**Comment by WinterSnowfall** [comment]
> DXVK 1.10.3 is the last version that works with my video card nvidia driver 470. 

On a sidenote, perhaps then consider using [dxvk-sarek](https://github.com/pythonlover02/DXVK-Sarek), since that at least is somewhat checked against new versions of Wine/Proton. It's a fork of the old dxvk 1.10.3 branch with some backports from more recent versions, and works on Kepler GPUs.

**Comment by Augusto7743** [comment]
@WinterSnowfall 
Thanks for your reply sharing DXVK Sarek.

DXVK official and Sarek install file not has any install script. Only dlls.
Copying the files to correct wine directories not works and does the same error message not being possible load d3d9.dll.
That is weird because not was done any changes in wine configuration registry. Only replaced files.
DXVK official and Sarek is installed only copying the files or need DXVK official version install script ?

**Comment by WinterSnowfall** [comment]
@Augusto7743 Please see: https://github.com/doitsujin/dxvk?tab=readme-ov-file#how-to-use . The latest version of dxvk has also done away with an install script, simply because there were too many configurations to cater for and it was getting cumbersome to maintain. If you follow the above guide you shouldn't have any issues.

**Comment by Augusto7743** [comment]
Thanks for your reply.
I have done exactly copying and using native dll overrides and not work.
If using DXVK current version had to work even if GPU not has Vulkan 1.3 because will redirect to Mesa Vulkan drivers, but not work and continue showing not is possible load d3d9 in d3d10 games or only opengl.
DXVK current version works in WINE 10.14 ?

**Comment by WinterSnowfall** [comment]
>  but not work and continue showing not is possible load d3d9 in d3d10 games or only opengl. 

You should not get any loading errors if things are set up properly, not sure what is going on in your prefix. That being said, it's not like anyone is testing 1.10.3 these days.

> DXVK current version works in WINE 10.14 ?

I am on Wine Staging 10.14 and both (latest) dxvk and dxvk-sarek work without issue over here.

**Comment by Augusto7743** [comment]
Here Ubuntu 20.04.1 and WINE staging 10.14.
However the WINE prefix directory are using symbolic link from /opt/WINE to /home/username/.wine because my home partition has less of 500 MB free space.
I have used WINE prefix using symbolic link for years and never had any issues.

**Comment by WinterSnowfall** [comment]
> I have used WINE prefix using symbolic link for years and never had any issues.

That is not the problem. I have both ~/.wine as a softlink as well as all the dxvk replaced files in system32/syswow64 as softlinks to another folder where I just extract the dxvk packages. I would suggest to try it out on a new prefix, just as an experiment at least, but unless reports start flowing in from all the corners of the world, or at least someone else can reproduce it, I can only surmise the issue is local.
