### ISSUE TITLE
ubuntu 18.04 compilation failed

### ISSUE THREAD

**Issue by legluondunet** [doitsujin/dxvk#532]
Hello,

I tried to compile DXVK on Ubuntu 18.04 and I obtain several errors:

```
$ sudo apt install mingw-w64 libvulkan-dev
$ git clone https://github.com/doitsujin/dxvk.git
$ cd dxvk
$ ./package-release.sh master test --no-package
```

I obtain my first error message:
```
Program glslangValidator found: NO

meson.build:48:0: ERROR: Program(s) ['glslangValidator'] not found or not executable
```
I searched on Ubuntu wich package contains 'glslangValidator' to install it and I found no one.
I searched on my hard disk if I already have a file named 'glslangValidator':

```
$ locate 'glslangValidator'
.../rpcs3/rpcs3/Vulkan/glslang/Test/glslangValidator
.../mame/3rdparty/bgfx/3rdparty/glslang/Test/glslangValidator
.../RetroArch/deps/glslang/glslang/Test/glslangValidator

```

I copied the glslangValidator from Retroarch to dxvk git root folder, launch again the compilation, this first error gone but I obtained a new one:

```
...
../../../src/util/com/../../d3d11/../dxvk/dxvk_device.h: In member function ‘void dxvk::DxvkDevice::unlockSubmission()’:
../../../src/util/com/../../d3d11/../dxvk/dxvk_device.h:348:7: error: ‘m_submissionLock’ was not declared in this scope
       m_submissionLock.unlock();
       ^~~~~~~~~~~~~~~~
../../../src/util/com/../../d3d11/../dxvk/dxvk_device.h:348:7: note: suggested alternative: ‘m_submissionQueue’
       m_submissionLock.unlock();
       ^~~~~~~~~~~~~~~~
       m_submissionQueue
ninja: build stopped: subcommand failed.

```

Thank you for your help.

**Comment by legluondunet** [comment]
I join you the full log.
[dxvk_compilation.log](https://github.com/doitsujin/dxvk/files/2259543/dxvk_compilation.log)

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk#troubleshooting

**Comment by SveSop** [comment]
@legluondunet dxvk builds on 18.04 with the mingw fix that @doitsujin linked.

I also use VulkanSDK 1.1.77.0 for my glslangValidator tho.

**Comment by legluondunet** [comment]
I made some progress:

1) I set POSIX alternatives for x86_64-w64-mingw32-gcc and x86_64-w64-mingw32-g++
2) compiled GlslangValidator from Vulkan SDK
3) copied it in the root git dxvk folder
4) launched the compilation script "./package-release.sh master test --no-package"

I obtained a half success: dxvk library in 64 bits format compiled OK, but not the 32 bits ones.
I joined you the compilation log result.
Do you have a suggestion about this issue?

[dxvk_compilation2.log](https://github.com/doitsujin/dxvk/files/2260471/dxvk_compilation2.log)

**Comment by Guy1524** [comment]
This is the exact same issue as you were having earlier, you only switched the _64_ bit mingw to the posix alternative, now you need to switch the 32 bit mingw.  Also, all the problems you are having are setup problems resulting from a failure to read the README and wiki pages, this kind of problem is not suitable for the bug tracker IMHO.

**Comment by legluondunet** [comment]
You are right Guy, it is not a bug. I did read the readme and wiki but it is not enough explained. I'll continue to ask help to the forum. Thanks anyway.

**Comment by SveSop** [comment]
@legluondunet The README lists `(use i686 for 32-bit):` :) So, yeah, it was not detailed enough to explain that you need to do both i guess.

You should also follow the VulkanSDK info, and look at the script included in the SDK. This explains how to set up your .profile file (your user profile), so that the libraries from the VulkanSDK is used (instead of copying stuff into the dxvk folder)

**Comment by legluondunet** [comment]
In fact I already choosed the two POSIX alternatives, like I explained in my last post. But  it works only for 64 bits library. I surely missed something. 
```

$ sudo update-alternatives --config x86_64-w64-mingw32-gcc
[sudo] Mot de passe de legluondunet : 
Il existe 2 choix pour l'alternative x86_64-w64-mingw32-gcc (qui fournit /usr/bin/x86_64-w64-mingw32-gcc).

  Sélection   Chemin                                 Priorité  État
------------------------------------------------------------
  0            /usr/bin/x86_64-w64-mingw32-gcc-win32   60        mode automatique
* 1            /usr/bin/x86_64-w64-mingw32-gcc-posix   30        mode manuel
  2            /usr/bin/x86_64-w64-mingw32-gcc-win32   60        mode manuel

```
and
```
$ sudo update-alternatives --config x86_64-w64-mingw32-g++
Il existe 2 choix pour l'alternative x86_64-w64-mingw32-g++ (qui fournit /usr/bin/x86_64-w64-mingw32-g++).

  Sélection   Chemin                                 Priorité  État
------------------------------------------------------------
  0            /usr/bin/x86_64-w64-mingw32-g++-win32   60        mode automatique
* 1            /usr/bin/x86_64-w64-mingw32-g++-posix   30        mode manuel
  2            /usr/bin/x86_64-w64-mingw32-g++-win32   60        mode manuel


```

**Comment by SveSop** [comment]
@legluondunet 
That is NOT for 32-bit.. it is for gcc and g++ (two compilers). The 32 bit is:
`sudo update-alternatives --config i686-w64-mingw32-gcc`
and
`sudo update-alternatives --config i686-w64-mingw32-g++`

If you type: `sudo update-alternatives --get-selections|grep mingw32`
it should list:
```
i686-w64-mingw32-g++  manual  /usr/bin/i686-w64-mingw32-g++-posix
i686-w64-mingw32-gcc  manual  /usr/bin/i686-w64-mingw32-gcc-posix
x86_64-w64-mingw32-g++  manual  /usr/bin/x86_64-w64-mingw32-g++-posix
x86_64-w64-mingw32-gcc  manual  /usr/bin/x86_64-w64-mingw32-gcc-posix
```

**Comment by legluondunet** [comment]
Finally it's compiled. Thank you very much SveSop!

**Comment by nextgenthemes** [comment]
Just a question to clarify because the readme actually has two commands at the end. I actually need 4 commands to set all those 4 mentined to posix?

```
sudo update-alternatives --config i686-w64-mingw32-g++
sudo update-alternatives --config i686-w64-mingw32-gcc
sudo update-alternatives --config x86_64-w64-mingw32-g++
sudo update-alternatives --config x86_64-w64-mingw32-gcc
```

One of them gave me a warning that some symlink can not created but my build went fine. Today I run them again and no warning anymore. Maybe even the order is important?

**Comment by legluondunet** [comment]
Hello nextgenthemes,

" I actually need 4 commands to set all those 4 mentioned to posix?" --> yes
"One of them gave me a warning that some symlink can not created but my build went fine. " --> doesn't matter
"Maybe even the order is important" --> no.

**Comment by legluondunet** [comment]
@doitsujin could  you add in the troubleshooting section this commands:

sudo update-alternatives --config i686-w64-mingw32-g++
sudo update-alternatives --config i686-w64-mingw32-gcc
sudo update-alternatives --config x86_64-w64-mingw32-g++
sudo update-alternatives --config x86_64-w64-mingw32-gcc

instead of the "(use i686 for 32-bit)" reference that a lot of people don't know what it is about?
I think you have to precise, in first step, that the libvulkan library have to be installed in 32 AND 64 bits:
sudo apt-get install libvulkan-dev libvulkan-dev:i386
That is not precised in the requierement.

VXDK is more and more popular and a more precise documentation will avoid a lot of issue.
