### ISSUE TITLE
Build failure on Slackware 14.2

### ISSUE THREAD

**Issue by orbea** [doitsujin/dxvk#1035]
I am trying to build `dxvk` from source on `Slackware64-14.2` and am encountering build issues.
```
In file included from ../src/util/util_env.h:3:0,
                 from ../src/util/util_env.cpp:1:
../src/util/util_string.h:9:15: error: expected '{' before '::' token
 namespace dxvk::str {
               ^
../src/util/util_string.h:9:17: error: 'str' in namespace '::' does not name a type
 namespace dxvk::str {
                 ^
In file included from ../src/util/util_env.cpp:1:0:
../src/util/util_env.h:5:15: error: expected '{' before '::' token
 namespace dxvk::env {
               ^
../src/util/util_env.h:5:17: error: 'env' in namespace '::' does not name a type
 namespace dxvk::env {
                 ^
../src/util/util_env.cpp:5:15: error: expected '{' before '::' token
 namespace dxvk::env {
               ^
../src/util/util_env.cpp:5:17: error: 'env' in namespace '::' does not name a type
 namespace dxvk::env {
                 ^
../src/util/util_env.cpp:54:1: error: expected '}' at end of input
 }
 ^
../src/util/util_env.cpp:54:1: error: expected '}' at end of input
../src/util/util_env.cpp:54:1: error: expected '}' at end of input
```
I am building `dxvk` like this which works on the more recent developmental `Slackware64-current`. Unfortunately it would help a lot if this also worked on the older release so that `dxvk` can be added to slackbuilds.org.
```
  meson \
    --cross-file=build-wine64.txt \
    -Dbuildtype=Release \
    build
ninja -C build
```

### System information
- OS: `Slackware64-14.2`
- Glibc version: `2.23`
- Wine version: `4.0`
- DXVK version: `1.0.3`
- Meson version: `0.49.0`
- Ninja version: `1.9.0`

### Log files
Build log: [dxvk.ninja.log](https://github.com/doitsujin/dxvk/files/3128593/dxvk.ninja.log)

**Comment by doitsujin** [comment]
From your log:
> `Cross C++ compiler: wineg++ (gcc 5.5.0)`

The build requirements clearly state MinGW 6.0 as a requirement, which includes GCC 8.0.

**Comment by orbea** [comment]
I suppose it builds on Slackware current without mingw because it has `gcc-8.3.0`? Its kind of unfortunate to not support older compilers when even vulkan-sdk will build with `gcc-5.5.0`, but its your call.

**Comment by Joshua-Ashton** [comment]
It doesn't really matter.
If you have compilers that are that old then your drivers are likely equally outdated.

**Comment by orbea** [comment]
> If you have compilers that are that old then your drivers are likely equally outdated.

Mesa (`11.2.2`) users may be out of luck, but the nvidia drivers (`418.56`) and vulkan-sdk (`1.1.106.0`) are recent. Of course obtaining a more modern mesa is far easier than a newer compiler for the average user.
